### ISSUE TITLE
Error on chargeCard

### ISSUE THREAD

**Issue by C-Spydo** [jogboms/flutter_ravepay#14]
I keep getting this error whenever I try using the plugin:

02-26 17:20:08.692 23729-23756/ng.com.cspydo.medcart E/flutter: [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
    MissingPluginException(No implementation found for method chargeCard on channel ng.i.handikraft/flutter_ravepay)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
    <asynchronous suspension>
    #1      Ravepay.chargeCard (package:flutter_ravepay/flutter_ravepay.dart:28:31)
    <asynchronous suspension>

**Comment by jogboms** [comment]
@C-Spydo I want to believe this is happening on iOS. See #12. Also related #13

**Comment by C-Spydo** [comment]
No, its happening on Android

**Comment by jogboms** [comment]
This really shouldn't be the case, can you try running the example project locally? @C-Spydo

**Comment by C-Spydo** [comment]
That was exactly what I did, tried it a few times too

**Comment by jogboms** [comment]
And you came up with the same error?

**Comment by C-Spydo** [comment]
Yeah
